apiVersion: minio.mxcd.dev/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: bucket
    app.kubernetes.io/instance: bucket-sample
    app.kubernetes.io/part-of: mc-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mc-controller
  name: bucket-sample
spec:
  # TODO(user): Add fields here
